/* MUSTER BAW SEBN • PPE — SPA navigation for GitHub Pages */
"use strict";
const PAGES={dashboard:"Tableau de bord",projects:"Gestion des projets","drawing-scanner":"Scanner le Drawing","ai-analyzer":"Analyseur IA","manual-analysis":"Analyse manuelle",connectors:"Connecteurs détectés","connector-3d":"Vue 3D Connecteur",pinout:"Pinout & Cavités","wire-list":"Wire List","wire-details":"Détails des fils",terminals:"Terminaux & Contacts",compatibility:"Compatibilité",validation:"Validation humaine",bom:"Génération BOM",reports:"Rapports & Historique",database:"Base de données",settings:"Paramètres"};
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const Toast={show(message,type="success"){const box=$("#toastContainer");if(!box)return;const el=document.createElement("div");el.className=`toast ${type} show`;el.innerHTML=`<i class="fa-solid ${type==="error"?"fa-circle-xmark":type==="warning"?"fa-triangle-exclamation":"fa-circle-check"}"></i><span>${message}</span>`;box.appendChild(el);setTimeout(()=>{el.classList.remove("show");setTimeout(()=>el.remove(),250)},3000)}};
const pageData={projects:["Gestion des projets","Créez, ouvrez et gérez vos projets MUSTER BAW.","fa-folder-open"],"drawing-scanner":["Scanner le Drawing","Importez un PDF ou une image de votre schéma de câblage.","fa-file-import"],"ai-analyzer":["Analyseur IA","Computer Vision pour détecter automatiquement les éléments du câblage.","fa-brain"],"manual-analysis":["Analyse manuelle","Vérifiez et complétez les données détectées par l’IA.","fa-diagram-project"],connectors:["Connecteurs détectés","Références, types, pins et cavités détectés.","fa-plug"],"connector-3d":["Vue 3D Connecteur","Visualisation du connecteur et de son orientation.","fa-cube"],pinout:["Pinout & Cavités","Table de correspondance des pins et cavités.","fa-table-cells"],"wire-list":["Wire List","Liste complète des fils analysés.","fa-grip-lines"],"wire-details":["Détails des fils","Couleur, section, longueur, direction, terminal et contact.","fa-magnifying-glass"],terminals:["Terminaux & Contacts","Gestion des terminaux et contacts compatibles.","fa-link"],compatibility:["Compatibilité","Contrôle Wire ↔ Terminal ↔ Connector.","fa-shield-halved"],validation:["Validation humaine","Validez ou corrigez les résultats de l’analyse IA.","fa-user-check"],bom:["Génération BOM","Préparez la nomenclature des composants.","fa-boxes-stacked"],reports:["Rapports & Historique","Consultez les analyses et exportez les rapports.","fa-file-lines"],database:["Base de données","Références connecteurs, terminaux, contacts et câbles.","fa-database"],settings:["Paramètres","Configuration de l’application et préférences utilisateur.","fa-gear"]};
function template(page){const d=pageData[page]||[PAGES[page],"Module MUSTER BAW.","fa-layer-group"];
 if(page==="drawing-scanner")return `<div class="page-header"><div><span class="page-label">ANALYSE</span><h2>${d[0]}</h2><p>${d[1]}</p></div></div><div class="dashboard-card"><div class="upload-zone"><div class="upload-zone-icon"><i class="fa-solid fa-cloud-arrow-up"></i></div><h3>Déposez votre Drawing ici</h3><p>PDF, PNG ou JPG — taille maximale 50 MB.</p><label class="btn btn-primary" for="drawingFile"><i class="fa-solid fa-file-import"></i>Choisir un fichier</label><input id="drawingFile" type="file" accept="application/pdf,image/png,image/jpeg" hidden></div></div>`;
 if(page==="wire-list")return `<div class="page-header"><div><span class="page-label">CÂBLAGE</span><h2>Wire List</h2><p>Résultats structurés de l’analyse des fils.</p></div><button class="btn btn-primary" id="exportWires"><i class="fa-solid fa-download"></i>Exporter JSON</button></div><div class="dashboard-card"><div class="table-container"><table class="data-table"><thead><tr><th>Wire</th><th>Pin</th><th>Connecteur</th><th>Couleur</th><th>Section</th><th>Longueur</th><th>Terminal</th><th>Contact</th></tr></thead><tbody>${[1,2,3,4,5].map(n=>`<tr><td><strong class="wire-number">W-${String(n).padStart(3,"0")}</strong></td><td>A${n}</td><td>CON-A12</td><td>RD/BK</td><td>0.35 mm²</td><td>${n*120} mm</td><td>TE-025</td><td>Contact-${n}</td></tr>`).join("")}</tbody></table></div></div>`;
 if(page==="connector-3d")return `<div class="page-header"><div><span class="page-label">CONNECTEURS</span><h2>${d[0]}</h2><p>${d[1]}</p></div></div><div class="viewer-3d"><div class="viewer-3d-grid"></div><div class="connector-3d-placeholder"></div></div>`;
 return `<div class="page-header"><div><span class="page-label">MUSTER BAW SEBN • PPE</span><h2>${d[0]}</h2><p>${d[1]}</p></div><button class="btn btn-primary"><i class="fa-solid ${d[2]}"></i>Ouvrir le module</button></div><div class="dashboard-grid"><div class="dashboard-card"><div class="ai-card-content"><div class="ai-icon"><i class="fa-solid ${d[2]}"></i></div><h4>${d[0]}</h4><p>Ce module fait partie du workflow MUSTER BAW : analyse, détection, compatibilité, validation et génération des résultats.</p><span class="ai-status"><span></span>Module opérationnel</span></div></div><div class="dashboard-card"><div class="card-header"><div><h3>Workflow</h3><p>Étape du processus</p></div></div><div class="workflow-list"><div class="workflow-item completed"><span class="workflow-number">01</span><div><strong>Import / Données</strong><small>Sources du projet</small></div><i class="fa-solid fa-circle-check"></i></div><div class="workflow-item active"><span class="workflow-number">02</span><div><strong>${d[0]}</strong><small>Traitement actuel</small></div><i class="fa-solid fa-spinner"></i></div><div class="workflow-item"><span class="workflow-number">03</span><div><strong>Validation & Résultats</strong><small>Étape suivante</small></div></div></div></div></div>`;
}
const Navigation={init(){document.addEventListener("click",e=>{const item=e.target.closest("[data-page],[data-page-link]");if(item){e.preventDefault();this.go(item.dataset.page||item.dataset.pageLink)}})},go(page){if(!PAGES[page])return;const target=document.getElementById(`page-${page}`);if(target&&page!=="dashboard"&&!target.dataset.ready){target.innerHTML=template(page);target.dataset.ready="1"}$$('.page').forEach(x=>{const active=x.id===`page-${page}`;x.classList.toggle("active",active);active?x.removeAttribute("hidden"):x.setAttribute("hidden","")});$$('.nav-item').forEach(x=>{const active=x.dataset.page===page;x.classList.toggle("active",active);x.setAttribute("aria-current",active?"page":"false")});const title=$("#pageTitle");if(title)title.textContent=PAGES[page];history.replaceState({page},"",`#${page}`);window.scrollTo({top:0,behavior:"smooth"});this.bind(page)},bind(page){if(page==="drawing-scanner"){const input=$("#drawingFile");if(input&&!input.dataset.bound){input.dataset.bound="1";input.onchange=()=>{const f=input.files[0];if(!f)return;const ok=["application/pdf","image/png","image/jpeg"].includes(f.type)&&f.size<=50*1024*1024;Toast.show(ok?`Drawing « ${f.name} » importé.`:"Format ou taille invalide.",ok?"success":"error")}}}if(page==="wire-list"){const b=$("#exportWires");if(b)b.onclick=()=>{const blob=new Blob([JSON.stringify({project:"MUSTER BAW",wires:[{id:"W-001",color:"RD/BK",section:"0.35 mm²",length:"120 mm"}]},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="muster-baw-wire-list.json";a.click();URL.revokeObjectURL(a.href);Toast.show("Wire List exportée.")}}}};
const Theme={init(){const b=$("#themeToggle");if(!b)return;this.apply(localStorage.getItem("musterTheme")||"light");b.onclick=()=>{const t=document.body.classList.contains("dark-mode")?"light":"dark";this.apply(t);localStorage.setItem("musterTheme",t);Toast.show(t==="dark"?"Mode sombre activé.":"Mode clair activé.")}},apply(t){document.body.classList.toggle("dark-mode",t==="dark");const i=$("#themeToggle i");if(i)i.className=t==="dark"?"fa-solid fa-sun":"fa-solid fa-moon"}};
const Sidebar={init(){const b=$("#mobileMenuButton"),s=$("#sidebar");if(b)b.onclick=()=>s.classList.toggle("mobile-open")}};
window.addEventListener("DOMContentLoaded",()=>{Navigation.init();Theme.init();Sidebar.init();const hash=location.hash.slice(1);Navigation.go(PAGES[hash]?hash:"dashboard")});
window.addEventListener("hashchange",()=>{const p=location.hash.slice(1);if(PAGES[p])Navigation.go(p)});
